-- 음식종류별
-- 즐겨찾기 수가 가장 많은 식당
-- 음식 종류, ID, 식당이름, 즐겨찾기 수 
SELECT FOOD_TYPE, REST_ID, REST_NAME,FAVORITES
FROM REST_INFO i1
WHERE FAVORITES in 
(
    SELECT max(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    HAVING i1.FOOD_TYPE = FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC