-- 년, 월, 성별 별
-- 회원수 출력

SELECT YEAR(o.SALES_DATE) as YEAR , MONTH(o.SALES_DATE) as MONTH, u.GENDER, count(DISTINCT u.USER_ID) as USERS
FROM ONLINE_SALE o
JOIN USER_INFO u
ON o.USER_ID = u.USER_ID and  not ISNULL(u.GENDER)
GROUP BY YEAR , MONTH, GENDER
ORDER BY YEAR , MONTH, GENDER