-- 노선별(ROUTE)
-- 노선, 총 누계 거리(역사이거리 총합), 평균 역사이 거리
SELECT ROUTE, CONCAT( ROUND(sum(D_BETWEEN_DIST),1), 'km') as TOTAL_DISTANCE
, CONCAT(ROUND( AVG (D_BETWEEN_DIST),2),'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(sum(D_BETWEEN_DIST),1) DESC