-- 분기별(QUARTER)
-- 분화된 대장균의 개체 총수(ECOLI_COUNT)
-- 각 분기에 Q 붙이기
SELECT CONCAT(FLOOR((MONTH(DIFFERENTIATION_DATE)-1)/3) +1, 'Q') as QUARTER ,count(*) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER 