-- 생산일자가 22/05 인 식품
-- ID, 식품이름 ,총매출 출력
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT)*p.PRICE as TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID AND DATE_FORMAT(o.PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , p.PRODUCT_ID

