-- 완료된 중고 거래의 총금액 >=70만원
-- 회원ID, 닉네임, 총거래금액
SELECT u.USER_ID, u.NICKNAME, sum(b.PRICE) as TOTAL_SALES
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD b
ON b.WRITER_ID = u.USER_ID
WHERE STATUS ='DONE'
GROUP BY u.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
