-- 부모의 형질을 모두 보유한
-- ID, 형질, 부모 대장균의 형질
SELECT e1.ID, e1.GENOTYPE, e1.GENOTYPE & e2.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA e1
JOIN ECOLI_DATA e2
ON e1.PARENT_ID = e2.ID
WHERE e1.GENOTYPE & e2.GENOTYPE = e2.GENOTYPE
ORDER BY e1.ID
-- & 연산했을때 부모와 같을것