-- 차종류가 '세단' 인것중
-- 10월에 대여 시작
-- 자동차 ID 출력 (중복없도록)
SELECT DISTINCT(c.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID 
WHERE MONTH(h.START_DATE) =10 and c.CAR_TYPE='세단' 
ORDER BY c.CAR_ID DESC