-- 물고기 종류별
-- 가장 큰
-- 물고기 ID, 이름, 길이
SELECT f.ID as ID, i.FISH_NAME as FISH_NAME, f.LENGTH as LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO i
ON f.FISH_TYPE = i.FISH_TYPE
WHERE f.LENGTH in (
    SELECT max(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING FISH_TYPE = f.FISH_TYPE
)
ORDER BY ID