-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID,r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_REPLY as r , USED_GOODS_BOARD as b
WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m')='2022-10' and b.BOARD_ID=r.BOARD_ID
ORDER BY r.CREATED_DATE, b.TITLE