-- 2022년 1월
-- 카테고리 별 도서 판매량 합산
-- 카테고리, 총판매량 출력
SELECT b.CATEGORY, sum(s.SALES) as TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY